### ISSUE TITLE
PropertyFieldListPicker - has a dependency on "@microsoft/sp-http" that is not declared in the manifest

### ISSUE THREAD

**Issue by MarkusLanger** [SharePoint/sp-dev-fx-property-controls#76]
#### Category
- [ ] Enhancement
- [x] Bug
- [ ] Question

#### Version
1.7.0

#### Expected / Desired Behavior / Question
A selection list when editing the webpart properties.

#### Observed Behavior
An error after adding the webpart to the page.
![image](https://user-images.githubusercontent.com/12131918/41523331-e8e3e95e-72d9-11e8-98fa-0c345129ed25.png)

`[SPLoaderError.loadComponentError]:
***Failed to load component "115bf84d-5af9-4ff7-88e3-8b2c8d192cdf" (BookmarksWebPart).
Original error: ***The entry point for component "115bf84d-5af9-4ff7-88e3-8b2c8d192cdf" (BookmarksWebPart) has a dependency on "@microsoft/sp-http" that is not declared in the manifest.

***INNERERROR:
***The entry point for component "115bf84d-5af9-4ff7-88e3-8b2c8d192cdf" (BookmarksWebPart) has a dependency on "@microsoft/sp-http" that is not declared in the manifest.
***CALLSTACK:
Error
    at t [as constructor] (https://spoprod-a.akamaihd.net/files/sp-client-prod_2018-06-08.007/sp-pages-assembly_en-us_17eeb54eb455f1d2680d2ddff54b1859.js:656:15770)
    at new t (https://spoprod-a.akamaihd.net/files/sp-client-prod_2018-06-08.007/sp-pages-assembly_en-us_17eeb54eb455f1d2680d2ddff54b1859.js:1401:22633)
    at Function.e.buildErrorWithVerboseLog (https://spoprod-a.akamaihd.net/files/sp-client-prod_2018-06-08.007/sp-pages-assembly_en-us_17eeb54eb455f1d2680d2ddff54b1859.js:1401:14508)
    at Function.e.buildLoadComponentError (https://spoprod-a.akamaihd.net/files/sp-client-prod_2018-06-08.007/sp-pages-assembly_en-us_17eeb54eb455f1d2680d2ddff54b1859.js:1401:10707)
    at https://spoprod-a.akamaihd.net/files/sp-client-prod_2018-06-08.007/sp-pages-assembly_en-us_17eeb54eb455f1d2680d2ddff54b1859.js:1401:65121`

***

**Content of my manifest.json**
`{
  "$schema": "https://developer.microsoft.com/json-schemas/spfx/client-side-web-part-manifest.schema.json",
  "id": "115bf84d-5af9-4ff7-88e3-8b2c8d192cdf",
  "alias": "BookmarksWebPart",
  "componentType": "WebPart",

  // The "*" signifies that the version should be taken from the package.json
  "version": "*",
  "manifestVersion": 2,

  // If true, the component can only be installed on sites where Custom Script is allowed.
  // Components that allow authors to embed arbitrary script code should set this to true.
  // https://support.office.com/en-us/article/Turn-scripting-capabilities-on-or-off-1f2c515f-5d7e-448a-9fd7-835da935584f
  "requiresCustomScript": false,

  "preconfiguredEntries": [{
    "groupId": "5c03119e-3074-46fd-976b-c60198311f70", // Other
    "group": { "default": "Other" },
    "title": { "default": "Bookmarks" },
    "description": { "default": "" },
    "officeFabricIconFontName": "Page",
    "properties": {
      "description": "Bookmarks"
    }
  }]
}`

***

##### The error does not appear in the local workbench.
![image](https://user-images.githubusercontent.com/12131918/41523416-3abacbf8-72da-11e8-9c5e-98c8889724a4.png)

#### Steps to Reproduce
1. Create a SPFx webpart
2. Install sp-dev-fx-property-controls package
3. Add PropertyFieldListPicker control as mentioned in https://sharepoint.github.io/sp-dev-fx-property-controls/controls/PropertyFieldListPicker/
4. Execute the app using gulp serve
5. Add the app to a page.

**Comment by MarkusLanger** [comment]
It works fine after a clean build and new deployment.
`gulp clean && gulp build && gulp package-solution`
